### ISSUE TITLE
ValueError when trying to add more price data

### ISSUE THREAD

**Issue by windowshopr** [adamjking3/Stock-Trading-Environment#1]
Love the article and love the walkthrough.

I'm having an issue though. I'm trying to add a bigger array with more information. I'm following a similar format to the AAPL.csv file, but I've made my own dataset with columns Time (instead of Date), Bid, BidSize, Last, LastSize, Ask, AskSize, and Volume. So I've amended the code to read:

`        # Prices contains the values for the last five prices
        self.observation_space = spaces.Box(
            low=0, high=1, shape=(8, 6), dtype=np.float16)

    def _next_observation(self):
        # Get the stock data points for the last 5 days and scale to between 0-1
        frame = np.array([
            self.df.loc[self.current_step: self.current_step +
                        LOOKBACK_PERIOD, 'Bid'].values / MAX_SHARE_PRICE,
            self.df.loc[self.current_step: self.current_step +
                        LOOKBACK_PERIOD, 'Last'].values / MAX_SHARE_PRICE,
            self.df.loc[self.current_step: self.current_step +
                        LOOKBACK_PERIOD, 'Ask'].values / MAX_SHARE_PRICE,
            self.df.loc[self.current_step: self.current_step +
                        LOOKBACK_PERIOD, 'BS'].values / MAX_BIDASK_SIZES,
            self.df.loc[self.current_step: self.current_step +
                        LOOKBACK_PERIOD, 'LS'].values / MAX_LAST_SIZE,
            self.df.loc[self.current_step: self.current_step +
                        LOOKBACK_PERIOD, 'AS'].values / MAX_BIDASK_SIZES,
            self.df.loc[self.current_step: self.current_step +
                        LOOKBACK_PERIOD, 'Volume'].values / MAX_NUM_SHARES,
        ])`

...I've assigned the MAX variables correctly in accordance to my new dataset. So my LOOKBACK_PERIOD = 5 currently, however I'm using (almost) tick data from the same day in my dataset, so I need it to have a further lookback period as there's a lot of data it should look at. In the AAPL.csv file, it uses daily ohlc prices, however in mine I'm using almost second by second data from one day. So I would like it to be able to lookback more than 5 timesteps, however when I change that number to something like 75, I receive this error:

`Traceback (most recent call last):
  File "main.py", line 20, in <module> model.learn(total_timesteps=20000)
  File "c:\users\...\desktop\python scripts\all tools\stable-baselines-master\stable_baselines\ppo2\ppo2.py", line 277, in learn
    runner = Runner(env=self.env, model=self, n_steps=self.n_steps, gamma=self.gamma, lam=self.lam)
  
File "c:\users\...\desktop\python scripts\all tools\stable-baselines-master\stable_baselines\ppo2\ppo2.py", line 399, in __init__
    super().__init__(env=env, model=model, n_steps=n_steps)
  
File "c:\users\...\desktop\python scripts\all tools\stable-baselines-master\stable_baselines\common\runners.py", line 19, in __init__
    self.obs[:] = env.reset()
  
File "c:\users\...\desktop\python scripts\all tools\stable-baselines-master\stable_baselines\common\vec_env\dummy_vec_env.py", line 45, in reset
    obs = self.envs[env_idx].reset()
  
File "C:\Users\...\Desktop\Python Scripts\Stock Market Prediction\Stock Trading Environment OpenAI Gym 2019\! - Matt's Attempt at Level 1\env\StockTradingEnv.py", line 158, in reset
    return self._next_observation()
  
File "C:\Users\...\Desktop\Python Scripts\Stock Market Prediction\Stock Trading Environment OpenAI Gym 2019\! - Matt's Attempt at Level 1\env\StockTradingEnv.py", line 85, in _next_observation
    ]], axis=0)
  
File "C:\Users\...\AppData\Local\Programs\Python\Python36\lib\site-packages\numpy\lib\function_base.py", line 4528, in append
    return concatenate((arr, values), axis=axis)
ValueError: all the input array dimensions except for the concatenation axis must match exactly`

Would you be able to shed some light on why I might be receiving this message? When I leave the lookback period to 5, it does run, however it doesn't place any trades so I think it just needs more of a lookback period to get a sense of what the prices are doing. Something to do with the axis???

Thanks a lot! Looking forward to the follow up articles for this!

**Comment by windowshopr** [comment]
Just tried to increase the look back period in the stock code from 5 to 6 and receive the same error. I know it has to do with the size of the array, but don't know how to fix it. Thanks!

**Comment by fightthepower** [comment]
I just look through your code and I think the error is in here `shape=(8, 6)` . If I am correct shape's format is (row,column) that is, it should be (6 days, 8 features) in your case its (8 features, 6 days).

**Comment by windowshopr** [comment]
@fightthepower Thanks for your input! Using just the stock code, when you change the lookback period from a 5 to a 6 for each, and then change it to read something like shape=(7, 6), I get the same error message. Try it out and let me know what you think, I'd really appreciate the help here :)

**Comment by fightthepower** [comment]
I initially thought the observations were stock prices and volume alone but it seems it also include the portfolio details also. The real problem was the line where we are appending the frame and the balance details. Because I really didn't understand the math behind it , take this solution a bit carefully.  I was able to run the code with these changes,

```
# Global variable
LOOKBACK_PERIOD=10 

# Observation space
self.observation_space = spaces.Box(
            low=0, high=1, shape=(LOOKBACK_PERIOD,6), dtype=np.float16)

# Method _next_observation with commented lines
def _next_observation(self):
    # Get the stock data points for the last 5 days and scale to between 0-1
    frame = np.array([
        self.df.loc[self.current_step: self.current_step +
                    LOOKBACK_PERIOD-1, 'Open'].values / MAX_SHARE_PRICE,
        self.df.loc[self.current_step: self.current_step +
                    LOOKBACK_PERIOD-1, 'High'].values / MAX_SHARE_PRICE,
        self.df.loc[self.current_step: self.current_step +
                    LOOKBACK_PERIOD-1, 'Low'].values / MAX_SHARE_PRICE,
        self.df.loc[self.current_step: self.current_step +
                    LOOKBACK_PERIOD-1, 'Close'].values / MAX_SHARE_PRICE,
        self.df.loc[self.current_step: self.current_step +
                    LOOKBACK_PERIOD-1, 'Volume'].values / MAX_NUM_SHARES,
    ])

    # Append additional data and scale each value to between 0-1
    # obs = np.append(frame, [[
        # self.balance / MAX_ACCOUNT_BALANCE,
        # self.max_net_worth / MAX_ACCOUNT_BALANCE,
        # self.shares_held / MAX_NUM_SHARES,
        # self.cost_basis / MAX_SHARE_PRICE,
        # self.total_shares_sold / MAX_NUM_SHARES,
        # self.total_sales_value / (MAX_NUM_SHARES * MAX_SHARE_PRICE),
    # ]], axis=0)
    
    obs=frame

    return obs

# Conditional statement
if self.current_step > len(self.df.loc[:, 'Open'].values) - LOOKBACK_PERIOD:
    self.current_step = 0

# Set the current step to a random point within the data frame
self.current_step = random.randint(0, len(self.df.loc[:, 'Open'].values) - LOOKBACK_PERIOD)
```

I have comment out the  line in `_next_observation` method which was used to append frame and portfolio details and I really don't know if this has any adverse effect on the portfolio calculations.

**Comment by windowshopr** [comment]
Thanks a lot @fightthepower . It does work. I'm going to leave the issue open to see if the author has any insights about the change maybe, or how to add a bigger dataset with a longer lookback period like I'm doing. Really appreciate it! I'll try to play with it now.

**Comment by windowshopr** [comment]
@fightthepower Actually, I found another great project from this author here that uses bitcoin data for a similar purpose:

https://github.com/notadamking/Bitcoin-Trader-RL

You can set a lookback period in the environment there, so I'm going to be playing with that one and see if I can merge the two methodologies together for my dataset. Thanks for your help!
