### ISSUE TITLE
env error, possible solution??

### ISSUE THREAD

**Issue by indhra** [adamjking3/Stock-Trading-Environment#8]
------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-11-e198ab9cfb61> in <module>()
      7 from stable_baselines import PPO2
      8 
----> 9 from env.StockTradingEnv import StockTradingEnv
     10 
     11 import pandas as pd

ModuleNotFoundError: No module named 'gym.Env'

---------------------------------------------------------------------------
NOTE: If your import is failing due to a missing package, you can
manually install dependencies using either !pip or !apt.

To view examples of installing some common dependencies, click the
"Open Examples" button below.

**Comment by Prasanna28Devadiga** [comment]
How was this fixed?
